# Generated by Django 4.2.7 on 2023-11-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_alter_booking_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='paid',
            new_name='total_amount_paid',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_amount_paid',
            field=models.BooleanField(default=False),
        ),
    ]
