# Generated by Django 4.2.7 on 2023-11-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_booking_payment_method_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='special_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
