# Generated by Django 4.2.7 on 2023-11-17 12:47

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0006_booking_special_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptour',
            name='from_country',
            field=django_countries.fields.CountryField(default='IN', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grouptour',
            name='to_country',
            field=django_countries.fields.CountryField(default='IN', max_length=2),
            preserve_default=False,
        ),
    ]
