# Generated by Django 4.2.7 on 2023-11-17 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0007_grouptour_from_country_grouptour_to_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='day',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)]),
        ),
    ]
