# Generated by Django 4.2.7 on 2023-11-20 08:16

import Web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0008_alter_itinerary_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Web.models.upload_path),
        ),
    ]
