# Generated by Django 4.2.7 on 2023-11-20 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0009_grouptour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
