# Generated by Django 4.2.7 on 2023-11-22 12:23

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0010_itinerary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptour',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
